version: '3.8'

services:
  app:
    build: .
    ports:
      - "8890:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ticklydb
      - SPRING_DATASOURCE_USERNAME=ddsys
      - SPRING_DATASOURCE_PASSWORD=07072022
    depends_on:
      - db
    networks:
      - tickly-network

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=ticklydb
      - POSTGRES_USER=ddsys
      - POSTGRES_PASSWORD=07072022
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tickly-network

networks:
  tickly-network:
    driver: bridge

volumes:
  postgres_data: